version: "2"
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - wsl
    - paralleltest
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/timkral5
  exclusions:
    rules:
      - path: ".*_test\\.go$"
        linters:
          - gochecknoglobals
