name: golangci-lint

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

permissions:
  contents: read
  # Optional: allow read access to pull requests. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | \
          sh -s -- -b $(go env GOPATH)/bin v2.4.0
      - name: create stub files
        run: |
          mkdir api/build; \
          mkdir api/build/html; \
          touch api/build/html/index.html; \
          mkdir api/build/html2; \
          touch api/build/html2/index.html
      - name: run linter
        run: make lint
